// artemis-snapshot bakes the static portion of Artemis' JS bootstrap
// into a V8 startup snapshot blob and writes it to js/snapshot.bin.
// The runtime then loads this blob via NewIsolateFromSnapshot, skipping
// the parse + first-evaluation cost of the bootstrap on every NewContext.
//
// What gets baked: every BootstrapSource js.BootstrapSources() returns,
// in order. Native callbacks like __wrap and document are stubbed so
// definition-time access does not throw; the real Go-bound versions
// overwrite the stubs in NewContext after the snapshot is loaded.
//
// Run from repo root: `go run ./cmd/artemis-snapshot/`.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	v8 "rogchap.com/v8go"

	"github.com/Christopher-Schulze/Artemis/js"
)

const snapshotPath = "js/snapshot.bin"
const snapshotManifestPath = "js/snapshot_manifest.json"
const artemisModulePath = "github.com/Christopher-Schulze/Artemis"

var stubsBootstrap = js.SnapshotStubBootstrap()

func main() {
	check := flag.Bool("check", false, "regenerate in memory and verify committed snapshot assets without writing")
	flag.Parse()
	if err := runMode(*check); err != nil {
		fmt.Fprintln(os.Stderr, "snapshot:", err)
		os.Exit(1)
	}
}

func runMode(checkOnly bool) error {
	start := time.Now()
	if err := validateModuleRoot("."); err != nil {
		return err
	}
	input, err := js.BuildSnapshotInputManifest(stubsBootstrap)
	if err != nil {
		return err
	}
	blob, err := generateSnapshot()
	if err != nil {
		return err
	}
	manifest := js.NewSnapshotManifest(input, blob, v8.Version(), runtime.Version(), runtime.GOOS, runtime.GOARCH)
	manifestBytes, err := marshalManifest(manifest)
	if err != nil {
		return err
	}
	if checkOnly {
		if err := verifyCommittedAssets(blob, manifest, manifestBytes); err != nil {
			return err
		}
		fmt.Printf("snapshot: committed assets match regenerated bytes (%d bytes) in %s\n", len(blob), time.Since(start))
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(snapshotPath), 0o750); err != nil {
		return fmt.Errorf("create snapshot directory: %w", err)
	}
	if err := writeFileAtomic(snapshotPath, blob, 0o644); err != nil {
		return err
	}
	if err := writeFileAtomic(snapshotManifestPath, manifestBytes, 0o644); err != nil {
		return fmt.Errorf("publish snapshot manifest: %w", err)
	}
	fmt.Printf("snapshot: %s (%d bytes) + %s in %s\n", snapshotPath, len(blob), snapshotManifestPath, time.Since(start))
	return nil
}

func generateSnapshot() ([]byte, error) {

	// --predictable forces V8 to use a deterministic random seed and a
	// stable allocation strategy so the produced snapshot bytes are
	// reproducible across runs. Without it, hash seeds and pointer
	// values vary between invocations, yielding noisy git diffs every
	// time the snapshot is regenerated.
	v8.SetFlags("--predictable", "--predictable_gc_schedule", "--single-threaded", "--single_threaded_gc", "--random_seed=1", "--hash_seed=1", "--rehash_snapshot")

	sc := v8.NewSnapshotCreator()
	defer sc.Dispose()

	if err := sc.RunScript(stubsBootstrap, "<artemis-snapshot-stubs>"); err != nil {
		return nil, fmt.Errorf("stubs: %w", err)
	}

	for _, b := range js.BootstrapSources() {
		// BootstrapSources already excludes tainted bootstraps; keep this
		// loop simple. Each source is a self-contained IIFE so order only
		// matters for prototype dependencies (dom-bridge first).
		if err := sc.RunScript(b.Source, b.Name); err != nil {
			return nil, fmt.Errorf("bootstrap %s: %w", b.Name, err)
		}
	}

	blob, err := sc.CreateBlob()
	if err != nil {
		return nil, fmt.Errorf("CreateBlob: %w", err)
	}
	return blob, nil
}

func marshalManifest(manifest js.SnapshotManifest) ([]byte, error) {
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("snapshot manifest: encode: %w", err)
	}
	return append(data, '\n'), nil
}

func verifyCommittedAssets(generatedBlob []byte, generatedManifest js.SnapshotManifest, generatedManifestBytes []byte) error {
	committedBlob, err := os.ReadFile(snapshotPath)
	if err != nil {
		return fmt.Errorf("snapshot drift: read committed blob: %w", err)
	}
	if !bytes.Equal(committedBlob, generatedBlob) {
		return fmt.Errorf("snapshot drift: committed blob differs from regenerated bytes")
	}
	committedManifestBytes, err := os.ReadFile(snapshotManifestPath)
	if err != nil {
		return fmt.Errorf("snapshot drift: read committed manifest: %w", err)
	}
	committedManifest, err := js.DecodeSnapshotManifest(committedManifestBytes)
	if err != nil {
		return err
	}
	input, err := js.BuildSnapshotInputManifest(stubsBootstrap)
	if err != nil {
		return err
	}
	if err := js.ValidateSnapshotManifest(committedManifest, committedBlob, input, v8.Version(), runtime.Version(), runtime.GOOS, runtime.GOARCH); err != nil {
		return fmt.Errorf("snapshot drift: committed manifest invalid: %w", err)
	}
	if !bytes.Equal(committedManifestBytes, generatedManifestBytes) {
		return fmt.Errorf("snapshot drift: committed manifest differs from regenerated provenance")
	}
	if generatedManifest.SHA256 != committedManifest.SHA256 || generatedManifest.SourceSetSHA256 != committedManifest.SourceSetSHA256 {
		return fmt.Errorf("snapshot drift: generated and committed manifest identities differ")
	}
	return nil
}

func validateModuleRoot(root string) error {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return fmt.Errorf("read Artemis go.mod: %w", err)
	}
	want := "module " + artemisModulePath
	for _, line := range strings.Split(string(data), "\n") {
		if strings.TrimSpace(line) == want {
			return nil
		}
	}
	return fmt.Errorf("working directory is not the Artemis module root")
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) (returnErr error) {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".snapshot-*")
	if err != nil {
		return fmt.Errorf("create snapshot candidate: %w", err)
	}
	tmpPath := tmp.Name()
	defer func() {
		if removeErr := os.Remove(tmpPath); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
			returnErr = errors.Join(returnErr, fmt.Errorf("remove snapshot candidate: %w", removeErr))
		}
	}()
	if err := tmp.Chmod(mode); err != nil {
		return closeSnapshotCandidate(tmp, fmt.Errorf("chmod snapshot candidate: %w", err))
	}
	if _, err := tmp.Write(data); err != nil {
		return closeSnapshotCandidate(tmp, fmt.Errorf("write snapshot candidate: %w", err))
	}
	if err := tmp.Sync(); err != nil {
		return closeSnapshotCandidate(tmp, fmt.Errorf("sync snapshot candidate: %w", err))
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close snapshot candidate: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("publish snapshot: %w", err)
	}
	return nil
}

func closeSnapshotCandidate(tmp *os.File, operationErr error) error {
	if closeErr := tmp.Close(); closeErr != nil {
		return errors.Join(operationErr, fmt.Errorf("close snapshot candidate: %w", closeErr))
	}
	return operationErr
}
